spring.application.name=courierAndLogisticsTrackingSoftware

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:ShipmentDB}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:ravi}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect