spring.application.name=courierAndLogisticsTrackingSoftware

spring.datasource.url=${DATABASE_PUBLIC_URL:jdbc:postgresql://localhost:5432/ShipmentDB}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:ravi}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect